import type { NextPage } from 'next'
import Head from 'next/head'
import Features from '../components/Features'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import NextEvents from '../components/NextEvents'
import Stats from '../components/Stats'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>RPM Esports F1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <Hero />

      <NextEvents />

      <Features />

      <Footer />
    </div>
  )
}

export default Home
